# Text-to-Speech CLI Tool Configuration

# Default input text file path (relative to project root)
input_file: examples/input.txt

# Path for the translated text file (relative to project root)
translated_file: temp/translated.txt

# Directory to store generated audio files (relative to project root)
output_directory: temp

# Characters used to split the text into chunks
special_characters:
  - "."
  - "?"
  - "!"
  - ";"
  - ":"
  - '\n'

# Delimiter used in word boundary files.
# Use a multiline string if the delimiter contains newlines.
delimiter: |
  ***WORD_BOUNDARY***

# Maximum characters per chunk for translation (default: 5000)
# Google Translate has limits on text length per request
max_translate_chars: 5000
