# Text-to-Speech CLI Tool Configuration

# Default input text file path (relative to project root)
input_file: examples/input.txt

# Path for the translated text file (relative to project root)
translated_file: output_files/translated.txt

# Directory to store generated audio files (relative to project root)
output_directory: output_files

# Characters used to split the text into chunks
special_characters:
  - .
  - ?
  - !
  - ;
  - :
  - \n

# Delimiter used in word boundary files.
# Use a multiline string if the delimiter contains newlines.
delimiter: |
  ***WORD_BOUNDARY***

# Default TTS voice to use (e.g., en-US-AriaNeural)
# You can list available voices using `edge-tts --list-voices`
tts_voice: en-US-AriaNeural
