version: '3.8'

services:
  tts-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TTS_OUTPUT_DIRECTORY=/app/output_audio
      - TTS_INPUT_FILE=/app/examples/input.txt
      - TTS_TRANSLATED_FILE=/app/output_files/translated.txt
    volumes:
      - ./output_audio:/app/output_audio
      - ./output_files:/app/output_files
    command: python -m src.web_server --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tts-api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - TTS_OUTPUT_DIRECTORY=/app/output_files
      - TTS_INPUT_FILE=/app/examples/input.txt
      - TTS_TRANSLATED_FILE=/app/output_files/translated.txt
    volumes:
      - ./output_files:/app/output_files
    command: uvicorn src.api_server:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: tts-network