version: '3.8'

services:
  tts-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TTS_OUTPUT_DIRECTORY=/app/temp
      - TTS_INPUT_FILE=/app/examples/data/input.txt
      - TTS_TRANSLATED_FILE=/app/temp/translated.txt
    volumes:
      - ./temp:/app/temp
    command: python -m src.web_server --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: "40s"